apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    {{- include "spring-clinic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      repo: {{.Values.deployment.labels.repo}}
      app: {{.Values.deployment.labels.app}}
      package: {{.Values.deployment.labels.package}}
  template:
    metadata:
      labels:
        app: {{.Values.deployment.labels.app}}              
    spec:      
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image }}"
          ports:
            - name: http
              containerPort: 80
                protocol: TCP

