# Default values for spring-clinic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

deployment:
  image: omza10/spring-petclinic:latest
  labels:
    repo: sonar
    app: maven
    package: java
  name: sonar-deployment
service:
  type: ClusterIP
  port: 80:8080
  labels:
    repo: sonar
    app: maven
    package: java
  mysql:
    image: mysql:5.7
    ports: 3306:3306
    labels:
      repo: sonar
      app: maven
      package: java
    environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=petclinic
    - MYSQL_PASSWORD=petclinic
    - MYSQL_DATABASE=petclini